[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
headless = false
port = 8501
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
showErrorDetails = true
toolbarMode = "minimal"

[runner]
magicEnabled = true
postScriptGC = true
fastReruns = true
enforceSerializableSessionState = false

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"
