[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
showSidebarNavigation = false
showErrorDetails = true
toolbarMode = "minimal"
